spring:
  data:
    rest:
      basePath: /api
  jackson:
    time-zone: GMT+8
  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: update
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8081
