spring:
  datasource:
      url: jdbc:mysql://localhost:3306/warehouse?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: root
      password: Root2016
      driverClassName: com.mysql.jdbc.Driver
#  redis:
#    host: 127.0.0.1
#    port: 16379
#    password: sunon
#    database: 1
#  cache:
#    type: redis

mybatis-plus:
  global-config:
    #刷新mapper 调试神器
    refresh-mapper: true